import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import {  useEffect } from 'react';
import styles from '../styles/Home.module.css'
import Link  from 'next/link'
import {AiFillInstagram} from 'react-icons/ai'
import {AiFillFacebook} from 'react-icons/ai'
import {FaTiktok} from 'react-icons/fa'
import {AiFillYoutube} from 'react-icons/ai'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic'



let img1 = '/media/photos/IMG_0013.jpeg'

let img2 = '/media/photos/fotoSelton.jpg'
let img3 = '/media/photos/CamilaAmado.jpg'
let img4 = '/media/photos/zecaBrito1.jpg'
let img5 = '/media/photos/joaoBrandao.jpg'
let img6 = '/media/photos/danielHerz1.jpg'
let img7 = '/media/photos/FILMAGEM3.jpeg'
let img8 = '/media/photos/FILMAGEM7.jpeg'
let img9 = '/media/photos/IMG_6134.jpeg'
let img10 = '/media/photos/IMG_6074.jpeg'
let img11 = '/media/photos/IMG_6058.jpeg'
let img12 = '/media/photos/terno.jpeg'

// 

let svg = '/media/undraw_small_town_re_7mcn.svg'
let svg1 = '/media/undraw_people_search_re_5rre.svg'
let svg2 = '/media/undraw_investor_update_re_qnuu.svg'
// let video1 = '/media/pierrô_saiu_à_francesa_(5) (2160p).mp4' 


let startX;
let scrollLeft = 0; 
let isDown = true;


export default function Home() {

    
 
  useEffect(()=>{ 
    // console.log(window.document)
    // console.log(styles.macrocontainer)
    const slider = document.querySelector("."+styles.macrocontainer) 
    // console.log(slider)
    if (slider !== null){     
      //  console.log('hi')
        slider.addEventListener('mousedown', (e)=>{       
        isDown = true  
        startX = e.pageX         
        scrollLeft = + slider.style.transform.match(/-?\d+/g)  
        
   
  });    
  slider.addEventListener('mouseleave', ()=>{
   isDown= false      
  });
  slider.addEventListener('mouseup', ()=>{
  isDown= false   
  });
  slider.addEventListener('mousemove', (e)=>{
   if(!isDown)return
  e.preventDefault();
    const x = e.pageX
  
    const walk = x - startX;    
    document.querySelector("."+styles.macrocontainer).style.transform="translateX("+(scrollLeft + walk) +"px)"      
  });

}} 
  , []); 
  
  
  // useEffect(()=>{ 
  //     const slider = document.querySelector(styles['macrocontainer'])
    
  //     if (slider === null){
  //       return
  //     }
  //     slider.addEventListener('touchstart', (e)=>{
  //       isDown = true  
  //       startX = e.changedTouches[0].pageX    
        
      
  //       scrollLeft = + slider.style.transform.match(/-?\d+/g)[0]     
  //     });    
  //   slider.addEventListener('touchend', ()=>{
  //      isDown= false      
  //   });
    
  //   slider.addEventListener('touchmove', (e)=>{
  //    if(!isDown)return
  //    e.preventDefault();
  //       const x = e.changedTouches[0].pageX    
  //       const walk = x - startX;    
  //       document.querySelector(styles['macrocontainer']).style.transform="translateX("+(scrollLeft + walk) +"px)"      
  //    });
  //   }, []);  


   


  return (
    <div className={styles.body}>
      <Head>
        <title>Helena Rache</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className={styles['intro']}>

        <div className={styles['herointro']}>
          <div className={styles['herointrotitle']} >
            Helena
          </div>
          {/* <div className={styles['herointrotext']}>
            Psicologia, teatro
          </div> */}          
        </div>

        <div className={styles['videointro']}>        
          {/* <video muted loop autoPlay>
              <source src={video1} />            
          </video> */}
        </div>
        
      
      </div>

      
      <div className={styles['macrocontainer'] }  >
        <div className={styles['teasertext']}>
            <div className={styles['teasertext__title']}  >
             Todo mundo tem a sua história...
            </div>
            <div className={styles['teasertext__body']}>
              Conheça um pouquinho da minha...
            </div>
        </div>
          <div className={styles['container']}>    
             <div className={styles['image__container']}>
                <Image src={img1} width={500} height={500} className={styles['imagehelena']} />              
              </div>
              <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  Artes Cênicas
                </div>                 
                <div className={styles['teaser__body-content']}>
                  Nas artes cênicas aprendi a dar voz e vida à muitos personagens
                </div>              
              </div>   
             
          </div>   


          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img2} className={styles['imagehelena']} />
                     </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                
                </div>                 
                <div className={styles['teaser__body-content']}>
                 Com a ajuda de grandes referências nas artes cênicas como Selton Mello
                </div>              
              </div>       
          </div>     

          <div className={styles['container wider']}>
              <div className={styles['image__container']}>
                <Image width={500} height={500} src={img3} className={styles['imagehelena']} /> 
              </div>              
             <div className={styles['teaser__body']}>              
                {/* <div className={styles['teaser__body-title']}>
                  2016
                </div>  */}                
                <div className={styles['teaser__body-content']}>
                  Minha mentora e atriz Camila Amado
                </div>
              
              </div>                 
          </div>              
          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img4} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                 Com os talentosos diretores como Zeca Brito... 
                </div>
              
              </div>   
             
         
          </div>     
          
                   
          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img5} className={styles['imagehelena']} />              
              </div>
              <div className={styles['teaser__body']}>               
            
                <div className={styles['teaser__body-content']}>
                   João Brandão
                  </div>
               </div>
          </div>              
          <div className={styles['container']}>
             <div className={styles['image__container']}>
                <Image width={500} height={500} src={img6} className={styles['imagehelena']} />              
              </div>
              <div className={styles['teaser__body']}>               
            
              <div className={styles['teaser__body-content']}>
                 Daniel Herz
                </div>
             </div>
               
          </div>     


          <div className={styles['container wider']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img7} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                e tantos outros profissionais com quem pude realizar lindos trabalhos...
                </div>
              
              </div>   
             
         
          </div>     

          <div className={styles['container ']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img8} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                
                </div>
              
              </div>   
             
         
          </div>     



          <div className={styles['container wider']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img9} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                Nestes seis anos, aprendi a ter um olhar cuidadoso para com o outro
                </div>              
              </div>   
             
         
          </div>     
              
          
        

          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img10} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                 Observar sem julgamento, experimentar outras vidas com carinho. Isso tudo me fez ser a profissional que sou hoje
                </div>              
              </div>  
          </div> 

        

          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img11} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>
                  
                </div> 
                
                <div className={styles['teaser__body-content']}>
                 No palco pude sentir o amor e a dor de vários personagens... 
                
                </div>              
              </div>  
          </div> 

          <div className={styles['container']}>
            <div className={styles['image__container']}>
                <Image width={500} height={500} src={img12} className={styles['imagehelena']} />
                </div>            
             <div className={styles['teaser__body']}>              
                <div className={styles['teaser__body-title']}>                  
                </div> 
                
                <div className={styles['teaser__body-content']}>                
                 A minha história me fez ter ter um olhar diferenciado na psicologia
                </div>              
              </div>  
          </div> 


      </div>
                        
        <div className={styles['herosection']} >     
            <div className={styles['heroimg']}>
            <Image width={500} height={500} src={svg} alt={styles['']} className='hero__img'/>
            </div> 
            <div className={styles['herotext']}>
                <div className={styles['hero__title']}>
                Administração           
                </div>
                <div className={styles['hero__teaser']}>
                    A gente sabe fazer, são 30 anos de experiência e
                    sempre crescendo.        
                </div>
                    <div className={styles['hero__button']}>
                    Saiba mais
                    </div>
         </div>      

       </div>

       <div className={styles['herosection1']}  >    
                <div className={styles['herotext1']}>

                   <div className={styles['hero__title1']}>
                    Acesso             
                    </div>
                    <div className={styles['hero__teaser1']}>
                      segunda via, extratos
                      <p>buscamos transparência</p>
                    </div>
               </div>
               <div className={styles['heroimg1']}>
                <Image width={500} height={500} src={svg1} alt="" className='hero__img1'/>
               </div> 
             </div>
      

                        
             <div className={styles['herosection']}>    
               <div className={styles['heroimg']}>
                <Image width={500} height={500} src={svg2} alt="" className='hero__img'/>
               </div> 
                <div className={styles['herotext']}>
                   <div className={styles['hero__title']}>
                    Tecnologia         
                    </div>
                    <div className={styles['hero__teaser']}>
                    Estamos online, buscando as melhores formas
                    para resolver problemas       
                    </div>
                    <a  className={styles['hero__button']} href='/cursos'>
                    Saiba mais
                    </a>
               </div>
             </div>

        <div className={styles['contactSection']}>                 

          <div className={styles['contactWrapper']}>        
              
            <div className={styles['socialMedia']}>  
                  <a href='/' className={styles['socialMedium']}> 
                      <AiFillYoutube className={styles['socialMediumIcon']}/> 
                  </a>
                  <a href='/' className={styles['socialMedium']}>                      
                      <AiFillInstagram className={styles['socialMediumIcon']}/>                                       
                  </a>
                  <a href='/'  className={styles['socialMedium']}>                       
                    <FaTiktok className={styles['socialMediumIcon']}/>                        
                  </a>   
                  <a href='/' className={styles['socialMedium']}>                     
                    <AiFillFacebook className={styles['socialMediumIcon']}/>                     
                </a> 
            </div> 

            <div className={styles['contactTitle']}>
              <p>CONTATO</p> 
            </div>

            <div className={styles['contact']}> 
                <div className={styles['contactbody']}>
                  <p>Mande uma mensagem</p>
                  <div className={styles['contactName']}>
                    <h3>Nome <span className={styles['redText']}>*</span>                
                    </h3>              
                    <input type="text" className={styles['name']}/>
                  </div>        

                  <div className={styles['contactName']}>
                    <h3>Email <span className={styles['redText']}>*</span>                
                    </h3> 
                      <input type="text" className={styles['email']}/>
                  </div>
                  <div className={styles['contactMessage']}> 
                    <h3>Mensagem<span className={styles['redText']}>*</span>                
                    </h3> 
                    <input type="text" className={styles['message']}/>
                  </div>
                  <div className={styles['submitButton']}>
                    <p>
                      Enviar
                    </p>
                  
                  </div>
              </div>
          </div> 
        



         </div>
         
        </div>



      {/* <OverFooter/> */}
      <Footer/>





      

    </div>
  )
}

export async function getStaticProps(){
 return ({props:{
  article: null
 }})
}
